// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/lockbox/pkg/secret"
)

type SecretStore struct {
	CreateStub        func(context.Context, secret.Key, secret.Secret) error
	createMutex       sync.RWMutex
	createArgsForCall []struct {
		arg1 context.Context
		arg2 secret.Key
		arg3 secret.Secret
	}
	createReturns struct {
		result1 error
	}
	createReturnsOnCall map[int]struct {
		result1 error
	}
	GetStub        func(context.Context, secret.Key) (*secret.Secret, error)
	getMutex       sync.RWMutex
	getArgsForCall []struct {
		arg1 context.Context
		arg2 secret.Key
	}
	getReturns struct {
		result1 *secret.Secret
		result2 error
	}
	getReturnsOnCall map[int]struct {
		result1 *secret.Secret
		result2 error
	}
	ReEncryptStub        func(context.Context) error
	reEncryptMutex       sync.RWMutex
	reEncryptArgsForCall []struct {
		arg1 context.Context
	}
	reEncryptReturns struct {
		result1 error
	}
	reEncryptReturnsOnCall map[int]struct {
		result1 error
	}
	SearchStub        func(context.Context, string) (secret.SearchRecords, error)
	searchMutex       sync.RWMutex
	searchArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	searchReturns struct {
		result1 secret.SearchRecords
		result2 error
	}
	searchReturnsOnCall map[int]struct {
		result1 secret.SearchRecords
		result2 error
	}
	UpsertStub        func(context.Context, secret.Key, secret.Secret) error
	upsertMutex       sync.RWMutex
	upsertArgsForCall []struct {
		arg1 context.Context
		arg2 secret.Key
		arg3 secret.Secret
	}
	upsertReturns struct {
		result1 error
	}
	upsertReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *SecretStore) Create(arg1 context.Context, arg2 secret.Key, arg3 secret.Secret) error {
	fake.createMutex.Lock()
	ret, specificReturn := fake.createReturnsOnCall[len(fake.createArgsForCall)]
	fake.createArgsForCall = append(fake.createArgsForCall, struct {
		arg1 context.Context
		arg2 secret.Key
		arg3 secret.Secret
	}{arg1, arg2, arg3})
	stub := fake.CreateStub
	fakeReturns := fake.createReturns
	fake.recordInvocation("Create", []interface{}{arg1, arg2, arg3})
	fake.createMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *SecretStore) CreateCallCount() int {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	return len(fake.createArgsForCall)
}

func (fake *SecretStore) CreateCalls(stub func(context.Context, secret.Key, secret.Secret) error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = stub
}

func (fake *SecretStore) CreateArgsForCall(i int) (context.Context, secret.Key, secret.Secret) {
	fake.createMutex.RLock()
	defer fake.createMutex.RUnlock()
	argsForCall := fake.createArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *SecretStore) CreateReturns(result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	fake.createReturns = struct {
		result1 error
	}{result1}
}

func (fake *SecretStore) CreateReturnsOnCall(i int, result1 error) {
	fake.createMutex.Lock()
	defer fake.createMutex.Unlock()
	fake.CreateStub = nil
	if fake.createReturnsOnCall == nil {
		fake.createReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.createReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *SecretStore) Get(arg1 context.Context, arg2 secret.Key) (*secret.Secret, error) {
	fake.getMutex.Lock()
	ret, specificReturn := fake.getReturnsOnCall[len(fake.getArgsForCall)]
	fake.getArgsForCall = append(fake.getArgsForCall, struct {
		arg1 context.Context
		arg2 secret.Key
	}{arg1, arg2})
	stub := fake.GetStub
	fakeReturns := fake.getReturns
	fake.recordInvocation("Get", []interface{}{arg1, arg2})
	fake.getMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *SecretStore) GetCallCount() int {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	return len(fake.getArgsForCall)
}

func (fake *SecretStore) GetCalls(stub func(context.Context, secret.Key) (*secret.Secret, error)) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = stub
}

func (fake *SecretStore) GetArgsForCall(i int) (context.Context, secret.Key) {
	fake.getMutex.RLock()
	defer fake.getMutex.RUnlock()
	argsForCall := fake.getArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SecretStore) GetReturns(result1 *secret.Secret, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	fake.getReturns = struct {
		result1 *secret.Secret
		result2 error
	}{result1, result2}
}

func (fake *SecretStore) GetReturnsOnCall(i int, result1 *secret.Secret, result2 error) {
	fake.getMutex.Lock()
	defer fake.getMutex.Unlock()
	fake.GetStub = nil
	if fake.getReturnsOnCall == nil {
		fake.getReturnsOnCall = make(map[int]struct {
			result1 *secret.Secret
			result2 error
		})
	}
	fake.getReturnsOnCall[i] = struct {
		result1 *secret.Secret
		result2 error
	}{result1, result2}
}

func (fake *SecretStore) ReEncrypt(arg1 context.Context) error {
	fake.reEncryptMutex.Lock()
	ret, specificReturn := fake.reEncryptReturnsOnCall[len(fake.reEncryptArgsForCall)]
	fake.reEncryptArgsForCall = append(fake.reEncryptArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ReEncryptStub
	fakeReturns := fake.reEncryptReturns
	fake.recordInvocation("ReEncrypt", []interface{}{arg1})
	fake.reEncryptMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *SecretStore) ReEncryptCallCount() int {
	fake.reEncryptMutex.RLock()
	defer fake.reEncryptMutex.RUnlock()
	return len(fake.reEncryptArgsForCall)
}

func (fake *SecretStore) ReEncryptCalls(stub func(context.Context) error) {
	fake.reEncryptMutex.Lock()
	defer fake.reEncryptMutex.Unlock()
	fake.ReEncryptStub = stub
}

func (fake *SecretStore) ReEncryptArgsForCall(i int) context.Context {
	fake.reEncryptMutex.RLock()
	defer fake.reEncryptMutex.RUnlock()
	argsForCall := fake.reEncryptArgsForCall[i]
	return argsForCall.arg1
}

func (fake *SecretStore) ReEncryptReturns(result1 error) {
	fake.reEncryptMutex.Lock()
	defer fake.reEncryptMutex.Unlock()
	fake.ReEncryptStub = nil
	fake.reEncryptReturns = struct {
		result1 error
	}{result1}
}

func (fake *SecretStore) ReEncryptReturnsOnCall(i int, result1 error) {
	fake.reEncryptMutex.Lock()
	defer fake.reEncryptMutex.Unlock()
	fake.ReEncryptStub = nil
	if fake.reEncryptReturnsOnCall == nil {
		fake.reEncryptReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.reEncryptReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *SecretStore) Search(arg1 context.Context, arg2 string) (secret.SearchRecords, error) {
	fake.searchMutex.Lock()
	ret, specificReturn := fake.searchReturnsOnCall[len(fake.searchArgsForCall)]
	fake.searchArgsForCall = append(fake.searchArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.SearchStub
	fakeReturns := fake.searchReturns
	fake.recordInvocation("Search", []interface{}{arg1, arg2})
	fake.searchMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *SecretStore) SearchCallCount() int {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	return len(fake.searchArgsForCall)
}

func (fake *SecretStore) SearchCalls(stub func(context.Context, string) (secret.SearchRecords, error)) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = stub
}

func (fake *SecretStore) SearchArgsForCall(i int) (context.Context, string) {
	fake.searchMutex.RLock()
	defer fake.searchMutex.RUnlock()
	argsForCall := fake.searchArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *SecretStore) SearchReturns(result1 secret.SearchRecords, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	fake.searchReturns = struct {
		result1 secret.SearchRecords
		result2 error
	}{result1, result2}
}

func (fake *SecretStore) SearchReturnsOnCall(i int, result1 secret.SearchRecords, result2 error) {
	fake.searchMutex.Lock()
	defer fake.searchMutex.Unlock()
	fake.SearchStub = nil
	if fake.searchReturnsOnCall == nil {
		fake.searchReturnsOnCall = make(map[int]struct {
			result1 secret.SearchRecords
			result2 error
		})
	}
	fake.searchReturnsOnCall[i] = struct {
		result1 secret.SearchRecords
		result2 error
	}{result1, result2}
}

func (fake *SecretStore) Upsert(arg1 context.Context, arg2 secret.Key, arg3 secret.Secret) error {
	fake.upsertMutex.Lock()
	ret, specificReturn := fake.upsertReturnsOnCall[len(fake.upsertArgsForCall)]
	fake.upsertArgsForCall = append(fake.upsertArgsForCall, struct {
		arg1 context.Context
		arg2 secret.Key
		arg3 secret.Secret
	}{arg1, arg2, arg3})
	stub := fake.UpsertStub
	fakeReturns := fake.upsertReturns
	fake.recordInvocation("Upsert", []interface{}{arg1, arg2, arg3})
	fake.upsertMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *SecretStore) UpsertCallCount() int {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	return len(fake.upsertArgsForCall)
}

func (fake *SecretStore) UpsertCalls(stub func(context.Context, secret.Key, secret.Secret) error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = stub
}

func (fake *SecretStore) UpsertArgsForCall(i int) (context.Context, secret.Key, secret.Secret) {
	fake.upsertMutex.RLock()
	defer fake.upsertMutex.RUnlock()
	argsForCall := fake.upsertArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *SecretStore) UpsertReturns(result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	fake.upsertReturns = struct {
		result1 error
	}{result1}
}

func (fake *SecretStore) UpsertReturnsOnCall(i int, result1 error) {
	fake.upsertMutex.Lock()
	defer fake.upsertMutex.Unlock()
	fake.UpsertStub = nil
	if fake.upsertReturnsOnCall == nil {
		fake.upsertReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.upsertReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *SecretStore) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *SecretStore) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ secret.Store = new(SecretStore)
