// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"context"
	"sync"

	"github.com/bborbe/lockbox/pkg/api"
	"github.com/bborbe/lockbox/pkg/migrate"
)

type TeamVaultClient struct {
	GetRevisionDataStub        func(context.Context, string) (api.RevisionData, error)
	getRevisionDataMutex       sync.RWMutex
	getRevisionDataArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getRevisionDataReturns struct {
		result1 api.RevisionData
		result2 error
	}
	getRevisionDataReturnsOnCall map[int]struct {
		result1 api.RevisionData
		result2 error
	}
	ListSecretsStub        func(context.Context) ([]migrate.TeamVaultSecret, error)
	listSecretsMutex       sync.RWMutex
	listSecretsArgsForCall []struct {
		arg1 context.Context
	}
	listSecretsReturns struct {
		result1 []migrate.TeamVaultSecret
		result2 error
	}
	listSecretsReturnsOnCall map[int]struct {
		result1 []migrate.TeamVaultSecret
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *TeamVaultClient) GetRevisionData(arg1 context.Context, arg2 string) (api.RevisionData, error) {
	fake.getRevisionDataMutex.Lock()
	ret, specificReturn := fake.getRevisionDataReturnsOnCall[len(fake.getRevisionDataArgsForCall)]
	fake.getRevisionDataArgsForCall = append(fake.getRevisionDataArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetRevisionDataStub
	fakeReturns := fake.getRevisionDataReturns
	fake.recordInvocation("GetRevisionData", []interface{}{arg1, arg2})
	fake.getRevisionDataMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TeamVaultClient) GetRevisionDataCallCount() int {
	fake.getRevisionDataMutex.RLock()
	defer fake.getRevisionDataMutex.RUnlock()
	return len(fake.getRevisionDataArgsForCall)
}

func (fake *TeamVaultClient) GetRevisionDataCalls(stub func(context.Context, string) (api.RevisionData, error)) {
	fake.getRevisionDataMutex.Lock()
	defer fake.getRevisionDataMutex.Unlock()
	fake.GetRevisionDataStub = stub
}

func (fake *TeamVaultClient) GetRevisionDataArgsForCall(i int) (context.Context, string) {
	fake.getRevisionDataMutex.RLock()
	defer fake.getRevisionDataMutex.RUnlock()
	argsForCall := fake.getRevisionDataArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *TeamVaultClient) GetRevisionDataReturns(result1 api.RevisionData, result2 error) {
	fake.getRevisionDataMutex.Lock()
	defer fake.getRevisionDataMutex.Unlock()
	fake.GetRevisionDataStub = nil
	fake.getRevisionDataReturns = struct {
		result1 api.RevisionData
		result2 error
	}{result1, result2}
}

func (fake *TeamVaultClient) GetRevisionDataReturnsOnCall(i int, result1 api.RevisionData, result2 error) {
	fake.getRevisionDataMutex.Lock()
	defer fake.getRevisionDataMutex.Unlock()
	fake.GetRevisionDataStub = nil
	if fake.getRevisionDataReturnsOnCall == nil {
		fake.getRevisionDataReturnsOnCall = make(map[int]struct {
			result1 api.RevisionData
			result2 error
		})
	}
	fake.getRevisionDataReturnsOnCall[i] = struct {
		result1 api.RevisionData
		result2 error
	}{result1, result2}
}

func (fake *TeamVaultClient) ListSecrets(arg1 context.Context) ([]migrate.TeamVaultSecret, error) {
	fake.listSecretsMutex.Lock()
	ret, specificReturn := fake.listSecretsReturnsOnCall[len(fake.listSecretsArgsForCall)]
	fake.listSecretsArgsForCall = append(fake.listSecretsArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.ListSecretsStub
	fakeReturns := fake.listSecretsReturns
	fake.recordInvocation("ListSecrets", []interface{}{arg1})
	fake.listSecretsMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *TeamVaultClient) ListSecretsCallCount() int {
	fake.listSecretsMutex.RLock()
	defer fake.listSecretsMutex.RUnlock()
	return len(fake.listSecretsArgsForCall)
}

func (fake *TeamVaultClient) ListSecretsCalls(stub func(context.Context) ([]migrate.TeamVaultSecret, error)) {
	fake.listSecretsMutex.Lock()
	defer fake.listSecretsMutex.Unlock()
	fake.ListSecretsStub = stub
}

func (fake *TeamVaultClient) ListSecretsArgsForCall(i int) context.Context {
	fake.listSecretsMutex.RLock()
	defer fake.listSecretsMutex.RUnlock()
	argsForCall := fake.listSecretsArgsForCall[i]
	return argsForCall.arg1
}

func (fake *TeamVaultClient) ListSecretsReturns(result1 []migrate.TeamVaultSecret, result2 error) {
	fake.listSecretsMutex.Lock()
	defer fake.listSecretsMutex.Unlock()
	fake.ListSecretsStub = nil
	fake.listSecretsReturns = struct {
		result1 []migrate.TeamVaultSecret
		result2 error
	}{result1, result2}
}

func (fake *TeamVaultClient) ListSecretsReturnsOnCall(i int, result1 []migrate.TeamVaultSecret, result2 error) {
	fake.listSecretsMutex.Lock()
	defer fake.listSecretsMutex.Unlock()
	fake.ListSecretsStub = nil
	if fake.listSecretsReturnsOnCall == nil {
		fake.listSecretsReturnsOnCall = make(map[int]struct {
			result1 []migrate.TeamVaultSecret
			result2 error
		})
	}
	fake.listSecretsReturnsOnCall[i] = struct {
		result1 []migrate.TeamVaultSecret
		result2 error
	}{result1, result2}
}

func (fake *TeamVaultClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *TeamVaultClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ migrate.TeamVaultClient = new(TeamVaultClient)
